name = "stapler-kun"
main = "src/index.ts"
compatibility_date = "2022-09-16"
node_compat = true

kv_namespaces = [
  { binding = "PINS", preview_id = "<INSERT HERE>", id = "<INSERT HERE>" }
]

[triggers]
crons = ["*/30 * * * *"]

[vars]
DISCORD_APPLICATION_ID = "<INSERT HERE>"
DISCORD_PUBLIC_KEY = "<INSERT HERE>"
DISCORD_TOKEN = "<INSERT HERE>"